/**
 * Hostinger Next.js Standalone Entry Point
 * 
 * Hostinger/Phusion Passenger looks for a root server.js file to start Node.js applications.
 * This file forwards the execution to the Next.js standalone server generated by the build process.
 * 
 * Using the standalone server reduces memory usage significantly, preventing 503 OOM errors.
 */

const path = require('path');
const fs = require('fs');

const standaloneServerPath = path.join(__dirname, '.next', 'standalone', 'server.js');

if (!fs.existsSync(standaloneServerPath)) {
  console.error("ERRO CRÍTICO: Arquivo standalone não encontrado!");
  console.error("Verifique se 'output: \"standalone\"' está no next.config.ts e se o build foi concluído.");
  process.exit(1);
}

// Inicia o servidor Next.js standalone
require(standaloneServerPath);
